source 'https://rubygems.org'

ruby '2.1.1'
gem 'rails', '4.0.4'

group :production do
  gem 'rails_12factor', '~> 0.0.2'
end

group :development, :test do
  gem 'dotenv-rails', '~> 0.10.0'
  gem 'better_errors', '~> 1.1.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'meta_request', '~> 0.2.8'
  gem 'debugger', '~> 1.6.1'
  gem 'rspec-rails', '~> 2.14.2'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem 'guard-rspec', '~> 4.2.8'
  gem 'guard-livereload', '~> 2.1.2', require: false
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-rescue', '~> 1.4.0'
  gem 'pry-stack_explorer'
  gem 'rack-mini-profiler', '~> 0.9.1'
  gem 'spring', '~> 1.1.2'
  gem 'flamegraph', '~> 0.0.5'
  gem 'memory_profiler', '~> 0.0.4'
  gem 'spring-commands-rspec', '~> 1.0.1'
  gem 'spring-commands-cucumber', '~>1.0.1'
  gem 'shoulda-matchers', '~> 2.5.0'
  gem 'faker', '~> 1.3.0'
  gem 'capybara', '~>2.2.1'
  gem 'database_cleaner', '~> 1.2.0'
  gem 'launchy', '~> 2.4.2'
  gem 'selenium-webdriver', '~> 2.41.0'
  gem 'railroady', '~> 1.1.1'
end

gem 'skylight', '~> 0.3.7'
gem 'sass-rails',   '~> 4.0.2'
gem 'coffee-rails', '~> 4.0.1'
gem 'uglifier', '>= 2.4.0'
gem 'compass-rails', '~> 1.1.7'
gem 'foundation-rails', '~> 5.2.2'
gem 'pg', '~> 0.17.1'
gem 'pg_search', '~> 0.7.3'
gem 'breadcrumbs_on_rails', '~> 2.3.0'
gem 'aasm', '~> 3.1.1'
gem 'haml-rails', '~> 0.5.3'
gem 'jquery-rails', '~> 3.1.0'
gem 'jquery-ui-rails', '~> 4.2.0'
gem 'carrierwave', '~> 0.10.0'
gem 'mini_magick', '~> 3.7.0'
gem 'carrierwave_backgrounder', '~> 0.3.0'
gem 'unf','~> 0.1.3'
gem 'sidekiq', '~> 3.0.0'
gem 'fog', '~> 1.21.0'
gem 'twitter_cldr', '~> 3.0.0'
gem 'kaminari', '~> 0.15.1'
gem 'devise', '~> 3.2.4'
gem 'newrelic_rpm', "~> 3.7.3"
gem 'foreman', '~> 0.63.0'
gem 'puma', '~> 2.8.1'
gem 'jbuilder', '~> 2.0.5'
gem 'virtus', '~> 1.0.2'
gem 'draper', '~> 1.3.0'
gem 'pundit', '~> 0.2.2'
gem 'public_activity', '~> 1.4.1'
# Deploy with Capistrano
