source 'https://rubygems.org'

ruby '2.1.3'
gem 'rails', '4.1.6'

group :production do
  gem 'rails_12factor', '~> 0.0.3'
end

group :development               , :test do
  gem 'dotenv-rails'             , '~> 1.0.2'
  gem 'better_errors'            , '~> 2.0.0'
  gem 'binding_of_caller'        , '~> 0.7.2'
  gem 'meta_request'             , '~> 0.3.4'
  gem 'rspec-rails'              , '~> 3.1.0'
  gem 'factory_girl_rails'       , '~> 4.5.0'
  gem 'guard-rspec'              , '~> 4.3.1'  , require: false
  gem 'guard-livereload'         , '~> 2.3.1'  , require: false
  gem 'pry'                      , '~> 0.10.0'
  gem 'pry-rails'                , '~> 0.3.2'
  gem 'pry-rescue'               , '~> 1.4.1'
  gem 'pry-stack_explorer'       , '~> 0.4.9'
  gem 'pry-byebug'               , '~> 2.0.0'
  gem 'rack-mini-profiler'       , '~> 0.9.2'
  gem 'spring'                   , '~> 1.1.3'
  gem 'flamegraph'               , '~> 0.0.5'
  gem 'memory_profiler'          , '~> 0.0.4'
  gem 'spring-commands-rspec'    , '~> 1.0.2'
  gem 'spring-commands-cucumber' , '~>1.0.1'
  gem 'shoulda-matchers'         , '~> 2.7.0'
  gem 'faker'                    , '~> 1.4.2'
  gem 'capybara'                 , '~>2.4.1'
  gem 'database_cleaner'         , '~> 1.3.0'
  gem 'launchy'                  , '~> 2.4.2'
  gem 'selenium-webdriver'       , '~> 2.43.0'
  gem 'railroady'                , '~> 1.2.0'
end

gem 'sass-rails'               , '~> 4.0.3'
gem 'uglifier'                 , '~> 2.5.3'
gem 'compass-rails'            , '~> 2.0.0'
gem 'foundation-rails'         , '~> 5.4.5.0'
gem 'pg'                       , '~> 0.17.1'
gem 'pg_search'                , '~> 0.7.8'
gem 'breadcrumbs_on_rails'     , '~> 2.3.0'
gem 'aasm'                     , '~> 3.4.0'
gem 'haml-rails'               , '~> 0.5.3'
gem 'jquery-rails'             , '~> 3.1.2'
gem 'jquery-ui-rails'          , '~> 5.0.2'
gem 'carrierwave'              , '~> 0.10.0'
gem 'mini_magick'              , '~> 3.8.1'
gem 'carrierwave_backgrounder' , '~> 0.4.1'
gem 'unf'                      , '~> 0.1.3'
gem 'sidekiq'                  , '~> 3.2.6'
gem 'fog'                      , '~> 1.24.0'
gem 'twitter_cldr'             , '~> 3.1.0'
gem 'kaminari'                 , '~> 0.16.1'
gem 'devise'                   , '~> 3.4.0'
gem 'newrelic_rpm'             , "~> 3.9.6"
gem 'puma'                     , '~> 2.9.1'
gem 'jbuilder'                 , '~> 2.2.4'
gem 'virtus'                   , '~> 1.0.3'
gem 'draper'                   , '~> 1.4.0'
gem 'pundit'                   , '~> 0.3.0'
gem 'public_activity'          , '~> 1.4.2'
# Deploy with Capistrano
