source 'https://rubygems.org'

ruby '2.1.0'
gem 'rails', '4.0.2'

group :production do
  gem 'rails_12factor', '~> 0.0.2'
end

group :development, :test do
  gem 'better_errors', '~> 1.1.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'meta_request', '~> 0.2.8'
  gem 'debugger', '~> 1.6.1'
  gem 'rspec-rails', '~> 2.14.1'
  gem 'factory_girl_rails', '~> 4.4.0'
  gem 'guard-rspec', '~> 4.2.6'
  gem 'guard-livereload', '~> 2.1.1', require: false
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-rescue', '~> 1.3.1'
  gem 'pry-stack_explorer'
  gem 'rack-mini-profiler', '~> 0.9.0'
  gem 'spring', '~> 1.1.1'
  gem 'spring-commands-rspec', '~> 1.0.1'
  gem 'spring-commands-cucumber', '~>1.0.1'
  gem 'shoulda-matchers', '~> 2.5.0'
  gem 'faker', '~> 1.2.0'
  gem 'capybara', '~>2.2.1'
  gem 'database_cleaner', '~> 1.2.0'
  gem 'launchy', '~> 2.4.2'
  gem 'selenium-webdriver', '~> 2.39.0'
end

gem 'sass-rails',   '~> 4.0.1'
gem 'coffee-rails', '~> 4.0.1'
gem 'uglifier', '>= 2.4.0'
gem 'compass-rails', '~> 1.1.3'
gem 'foundation-rails', '~> 5.1.1'
gem 'pg', '~> 0.17.1'
gem 'pg_search', '~> 0.7.3'
gem 'breadcrumbs_on_rails', '~> 2.3.0'
gem 'aasm', '~> 3.1.0'
gem 'haml-rails', '~> 0.5.3'
gem 'jquery-rails', '~> 3.1.0'
gem 'jquery-ui-rails', '~> 4.1.1'
gem 'mini_magick', '~> 3.7.0'
gem 'carrierwave', '~> 0.9.0'
gem 'carrierwave_direct', '~> 0.0.13'
gem 'sidekiq', '~> 2.17.4'
gem 'fog', '~> 1.20.0'
gem 'twitter_cldr', '~> 2.4.2'
gem 'kaminari', '~> 0.15.1'
gem 'devise', '~> 3.2.2'
gem 'dotenv-rails', '~> 0.9.0'
gem 'newrelic_rpm', "~> 3.7.2"
gem 'foreman', '~> 0.63.0'
gem 'puma', '~> 2.7.1'
gem 'jbuilder', '~> 2.0.2'
gem 'virtus', '~> 1.0.1'
gem 'draper', '~> 1.3.0'
# Deploy with Capistrano
# gem 'capistrano'
