development:
  adapter: postgresql
  encoding: unicode
  database: assethound_development
  pool: 5
  timeout: 5000
  username: fangari
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: assethound_test
  pool: 5
  timeout: 5000
  username: fangari
  password:
  host: localhost
