class CreateInventories < ActiveRecord::Migration
  def change
    create_table :inventories do |t|
      t.references :inspection
      t.boolean :kilometers
      t.boolean :villare
      t.boolean :glove_compartment
      t.boolean :dashboard
      t.boolean :right_seat
      t.boolean :left_seat
      t.boolean :back_seat
      t.boolean :third_row
      t.boolean :courtesy_light
      t.boolean :seat_belt
      t.string :radio_brand
      t.boolean :cd_player
      t.integer :speakers
      t.boolean :lighter
      t.integer :ash_trays
      t.boolean :clock
      t.integer :door_panels
      t.integer :rearview_mirrors
      t.integer :head_rest
      t.boolean :handles
      t.boolean :horn
      t.integer :side_mirrors
      t.boolean :warranty_book
      t.boolean :driver_manual
      t.boolean :ignition
      t.boolean :battery
      t.boolean :engine_operation
      t.boolean :uniq_form
      t.boolean :tax_receipt
      t.boolean :lights
      t.boolean :directional_signals
      t.boolean :external_fog_lights
      t.boolean :blind
      t.boolean :front_bumper
      t.boolean :hood
      t.boolean :wiper_blades
      t.boolean :front_right_fender
      t.boolean :front_right_door
      t.boolean :back_right_door
      t.boolean :right_stirrup
      t.boolean :back_right_fender
      t.boolean :back_bumper
      t.boolean :trunk_door
      t.boolean :back_left_fender
      t.boolean :back_left_door
      t.boolean :front_left_door
      t.boolean :left_stirrup
      t.boolean :canvas_hood
      t.boolean :top
      t.boolean :jack
      t.boolean :bolt_wrench
      t.integer :tool_kit
      t.integer :tool_keys
      t.boolean :front_tires
      t.boolean :back_tires
      t.boolean :spare_tires
      t.integer :common_rims
      t.integer :luxury_rims
      t.integer :cups
      t.boolean :front_windshield
      t.boolean :front_right_window
      t.boolean :rear_right_window
      t.boolean :third_rear_right_window
      t.boolean :rear_windshield
      t.boolean :rear_left_window
      t.boolean :front_left_window
      t.boolean :third_rear_left_window
      t.boolean :air_conditioner
      t.integer :electric_windows
      t.integer :central_block
      t.boolean :sun_roof
      t.boolean :luxury_steering_wheel
      t.integer :floor_mats
      t.integer :triangles
      t.boolean :first_aid_kit
      t.boolean :leather_upholstery
      t.boolean :pijama
      t.boolean :trunk_cover
      t.boolean :celular_phone
      t.boolean :electric_antena
      t.boolean :antena
      t.text :observations

      t.timestamps
    end
  end
end
