require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuildRestrictionsController do

  # This should return the minimal set of attributes required to create a valid
  # BuildRestriction. As you add validations to BuildRestriction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "kind_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuildRestrictionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all build_restrictions as @build_restrictions" do
      build_restriction = BuildRestriction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:build_restrictions).should eq([build_restriction])
    end
  end

  describe "GET show" do
    it "assigns the requested build_restriction as @build_restriction" do
      build_restriction = BuildRestriction.create! valid_attributes
      get :show, {:id => build_restriction.to_param}, valid_session
      assigns(:build_restriction).should eq(build_restriction)
    end
  end

  describe "GET new" do
    it "assigns a new build_restriction as @build_restriction" do
      get :new, {}, valid_session
      assigns(:build_restriction).should be_a_new(BuildRestriction)
    end
  end

  describe "GET edit" do
    it "assigns the requested build_restriction as @build_restriction" do
      build_restriction = BuildRestriction.create! valid_attributes
      get :edit, {:id => build_restriction.to_param}, valid_session
      assigns(:build_restriction).should eq(build_restriction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BuildRestriction" do
        expect {
          post :create, {:build_restriction => valid_attributes}, valid_session
        }.to change(BuildRestriction, :count).by(1)
      end

      it "assigns a newly created build_restriction as @build_restriction" do
        post :create, {:build_restriction => valid_attributes}, valid_session
        assigns(:build_restriction).should be_a(BuildRestriction)
        assigns(:build_restriction).should be_persisted
      end

      it "redirects to the created build_restriction" do
        post :create, {:build_restriction => valid_attributes}, valid_session
        response.should redirect_to(BuildRestriction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved build_restriction as @build_restriction" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuildRestriction.any_instance.stub(:save).and_return(false)
        post :create, {:build_restriction => { "kind_id" => "invalid value" }}, valid_session
        assigns(:build_restriction).should be_a_new(BuildRestriction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuildRestriction.any_instance.stub(:save).and_return(false)
        post :create, {:build_restriction => { "kind_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested build_restriction" do
        build_restriction = BuildRestriction.create! valid_attributes
        # Assuming there are no other build_restrictions in the database, this
        # specifies that the BuildRestriction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BuildRestriction.any_instance.should_receive(:update_attributes).with({ "kind_id" => "1" })
        put :update, {:id => build_restriction.to_param, :build_restriction => { "kind_id" => "1" }}, valid_session
      end

      it "assigns the requested build_restriction as @build_restriction" do
        build_restriction = BuildRestriction.create! valid_attributes
        put :update, {:id => build_restriction.to_param, :build_restriction => valid_attributes}, valid_session
        assigns(:build_restriction).should eq(build_restriction)
      end

      it "redirects to the build_restriction" do
        build_restriction = BuildRestriction.create! valid_attributes
        put :update, {:id => build_restriction.to_param, :build_restriction => valid_attributes}, valid_session
        response.should redirect_to(build_restriction)
      end
    end

    describe "with invalid params" do
      it "assigns the build_restriction as @build_restriction" do
        build_restriction = BuildRestriction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuildRestriction.any_instance.stub(:save).and_return(false)
        put :update, {:id => build_restriction.to_param, :build_restriction => { "kind_id" => "invalid value" }}, valid_session
        assigns(:build_restriction).should eq(build_restriction)
      end

      it "re-renders the 'edit' template" do
        build_restriction = BuildRestriction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuildRestriction.any_instance.stub(:save).and_return(false)
        put :update, {:id => build_restriction.to_param, :build_restriction => { "kind_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested build_restriction" do
      build_restriction = BuildRestriction.create! valid_attributes
      expect {
        delete :destroy, {:id => build_restriction.to_param}, valid_session
      }.to change(BuildRestriction, :count).by(-1)
    end

    it "redirects to the build_restrictions list" do
      build_restriction = BuildRestriction.create! valid_attributes
      delete :destroy, {:id => build_restriction.to_param}, valid_session
      response.should redirect_to(build_restrictions_url)
    end
  end

end
